version: '3.8'
services:
  api:
    build: .
    container_name: client-frontend-react-sneakers
    ports:
      - '2008:3000'
    volumes:
      - /app
    stdin_open: true
    tty: true
    network_mode: bridge